### PR TITLE
HDF5 backend improvements - part 1

### LINKED ISSUE #15: particle_single_constituent_name
I don't really understand why we put the constituent name into a single attribute (particle_single_constituent_name) and not a variable as in the Excel table particle_constituent_name(particle_constituent_number)? Again, for just one constituent it doesn't really matter but if I have 2 or 3 I have to generate more and more new attributes instead of having one variables which contains them all.

### LINKED ISSUE #16: particle_id
particle_id: Are we still aiming at using unique particle identifiers in the end? We could also add a second variable "particle_id_internal" which contains the name used by the developers but the particle_id itself is the "global" and unique identifier which is the only reliable "tag" attached to this structure.

### PR DESCRIPTION
**Pull request by rhoneyager**
Initially, icedb called the HDF5 C++ API. This API is unstable, and this caused problems with the build system. I've switched to the C API, and have written a large set of convenience classes for easily manipulating HDF5 objects. The eventual goal is to develop a standalone, header-only, C++ interface to HDF5 that is similar to Python's H5Py wrapper.

Icedb finally has support for writing tables of strings; this is used to complete the implementation of the 3-D shape structures program.

Further improvements to the HDF5 backend will improve support for reading and writing complex objects (like complex numbers). This will help with reading and writing scattering matrices.

Closes #15, closes #16. Already tested on Windows/MSVC 2017, Ubuntu 18.04/GCC 8, Ubuntu 16.04/GCC 7 (using Conda build system), RHEL 6 at PSU (custom GCC 8 build), Ubuntu 18.04/Clang 6.

Note: A C++17-compatible compiler is needed (will fix?). To easily get a recent compiler on older Linux distributions, one option is to install and use the [Conda Build System](https://rhoneyager.github.io/libicedb/install_using_conda.html).

Other errata:
- Older code for attributes, tables and groups now superseded.
- Older example apps are no longer built.
- apps/testing/core will be the location for unit tests using [Boost's Unit Testing Framework](https://www.boost.org/doc/libs/1_67_0/libs/test/doc/html/index.html). Not currently built, pending any further changes to the HDF5 backend.
- A separate merge will add the latest PSU file format changes.

### CODE REVIEW

**Comment by rhoneyager** [comment]
Hey @DaveOri, could you see if the code builds on your system? If you are using an Ubuntu version without a C++17 compiler, could you test the [Building using Conda](https://rhoneyager.github.io/libicedb/install_using_conda.html) instructions?

**Comment by DaveOri** [comment]
I have been able to compile the library fine with the conda build system (just to be specific I used anaconda3-5.2.0)
However when testing simple shapes from the example folders I get coredumps

```
(condaicedb) dori@dori-Aspire-E1-570G:~/develop/libicedb/build/RelWithDebInfo$ ./icedb-3d_structures_importer --from ../../share/examples/shapes/ADDA/sphere.geom --to sph.hdf5
Note: it is recommended that you set the metadata that describes the shapes that you are importing!
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140712839595840:
  #000: H5F.c line 511 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1604 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 413 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
terminate called without an active exception
Aborted (core dumped)
```

I am at ERAD at the moment and I have some difficulties in debugging.

**Comment by rhoneyager** [comment]
There was a line of code where I called openFile instead of createFile. For my testing sessions, I always had specified the --truncate option, which avoided that line of code. Oops.

Should work for you now.

**Comment by DaveOri** [comment]
Still having issues (sorry for the late reply, but now I moved to AMS in Vancouver)

```
(condaicedb) dori@dori-Aspire-E1-570G:~/develop/libicedb/build/RelWithDebInfo$ ./icedb-3d_structures_importer --config-file input.in 
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 140032770275136:
  #000: H5F.c line 418 in H5Fcreate(): invalid flags
    major: Invalid arguments to routine
    minor: Bad value
terminate called without an active exception
Aborted (core dumped)
```

**Comment by rhoneyager** [comment]
Oh. HDF5 no longer uses H5F_ACC_CREAT as an option, and not all of their documentation pages reflect this. Fixed.

**Comment by DaveOri** [comment]
Got ADDA shapes working but core dumps when trying ddscat-type files.
It seems core dumps are caused at file reading. I can have a look at it later

**Comment by rhoneyager** [comment]
All of the DDSCAT and ADDA sample files are working for me. For the ddscat-type files: some of the files have more than one constituent, and you need to specify the constituent ids on import. See the "constituent-names" program option. For example, --constituent-names=1-ice,2-water is valid input.

I changed the code so that the program reports on why a shape is invalid instead of just triggering a core dump. All of the changes have been applied to the master branch.

**Comment by DaveOri** [comment]
I confirm I still have problems with DDSCAT types. Also on the 1 constituent files.
```
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 139864467126080:
  #000: H5F.c line 511 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1604 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 630 in H5F__super_read(): truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048
    major: File accessibilty
    minor: File has been truncated
terminate called without an active exception
Aborted (core dumped)
```

But I can try to debug on the plane tomorrow.

**Pull request merged**
